# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
    themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
template: !include_dir_merge_list templates/

#cloudflared tunnel
http:
    use_x_forwarded_for: true
    trusted_proxies:
        - 172.30.33.0/24

# Custom Controls
lovelace:
    resources:
        - url: /local/custom_cards/solar_control/solar-control-card.js?v=1.1
          type: module

logger:
    default: warning
    logs:
        custom_components.tuya_ble: debug

# Fox ESS battery
sensor:
    - platform: foxess
      deviceID: 60HD15305ANM071
      deviceSN: 60HD15305ANM071
      apiKey: 670e24e9-8b5f-42fe-b506-eabcec3916ca
