# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
    themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
template: !include_dir_merge_list templates/

# Electricity tariff tracking
utility_meter: !include includes/utility_meters.yaml

counter:
    zerohero_credits:
        name: ZeroHero Daily Credits
        initial: 0
        step: 1
        restore: true

input_number:
    zerohero_window_start_reading:
        name: ZeroHero Window Start Reading
        min: 0
        max: 999999
        step: 0.01
        mode: box
        unit_of_measurement: kWh

#cloudflared tunnel
http:
    use_x_forwarded_for: true
    trusted_proxies:
        - 172.30.33.0/24

# Custom Controls
lovelace:
    resources:
        - url: /local/custom_cards/solar_control/solar-control-card.js?v=1.1
          type: module

logger:
    default: warning
    logs:
        custom_components.tuya_ble: debug

# Fox ESS battery
sensor:
    - platform: foxess
      deviceID: 60HD15305ANM071
      deviceSN: 60HD15305ANM071
      apiKey: 670e24e9-8b5f-42fe-b506-eabcec3916ca
